#!/usr/bin/env python3
"""
elfpack.py — ELF runtime packer (gaya UPX) untuk binary asli.

Dua mode:

  --mode static   In-memory loader untuk ET_EXEC / static binary.
                  Stub assembly (PIE, syscall langsung, tanpa libc):
                    mmap(range) -> decode tiap PT_LOAD (RLE+XOR) di p_vaddr
                    -> zero-fill bss -> mprotect per segment -> jmp e_entry.
                  Payload TIDAK pernah menyentuh disk. Stack (argc/argv/envp)
                  dibiarkan utuh dari kernel, jadi payload jalan normal.

  --mode dynamic  Temp-file loader untuk ET_DYN / dynamic binary (PIE,
                  linked libc — termasuk binary C++ seperti xcb).
                  Stub C (-static -nostdlib):
                    decode seluruh file ELF ke memori -> tulis file temp unik
                    /tmp/.elx_<pid> -> fork -> child execve (kernel loader
                    normal, PT_INTERP dihormati) -> parent wait4 + unlink.
                  File temp hanya hidup beberapa milidetik.

Keduanya pakai kompresi RLE (efektif untuk ELF: banyak byte 0) + XOR
1-byte key acak. Tiap run -> key & blob beda -> sha256 hasil beda.

Peringatan jujur: ini LAB studi teknik packing untuk binary sendiri.
RLE+XOR 1-byte bukan kripto kuat — hanya menyamarkan signature statis.
"""

import argparse
import hashlib
import os
import random
import struct
import subprocess
import sys
import tempfile

# Token placeholder @@X@@ dipakai karena assembly AT&T penuh karakter '$'
# (immediate) yang bentrok dengan string.Template / str.format.
def fill(tpl, mapping):
    for k, v in mapping.items():
        tpl = tpl.replace("@@" + k + "@@", str(v))
    return tpl


# ============================================================
# Stub static (assembly x86-64, AT&T) — in-memory ELF loader
# ============================================================
STUB_STATIC = """# generated by elfpack.py — static in-memory loader (PIE)
.section .text
.globl _start
_start:
    leaq blob(%rip), %rbx          # rbx = blob base
    leaq segs(%rip), %r14          # r14 = segmen table
    movq nsegs(%rip), %r13         # r13 = sisa segmen

    # mmap(range, PROT_RW, flags, -1, 0)
    movq $9, %rax
    movq @@MIN_V@@(%rip), %rdi
    movq @@RANGE@@(%rip), %rsi
    movq $3, %rdx
    movq @@FLAGS@@(%rip), %r10
    movq $-1, %r8
    xorq %r9, %r9
    syscall
    movq %rax, %r15                # base

seg_loop:
    movq %r15, %rdi
    addq 0(%r14), %rdi             # dst = base + off
    movq %rbx, %rsi
    addq 32(%r14), %rsi            # src = blob + blob_off
    movq 40(%r14), %rcx            # blob_len
    movq %rsi, %r12
    addq %rcx, %r12                # r12 = src end
    movb @@KEY@@(%rip), %r11b
    cmpq %r12, %rsi
    jae seg_fill

dec_loop:
    lodsb
    xorb %r11b, %al                # XOR decode
    testb $0x80, %al
    jnz dec_run
    stosb                          # literal
    cmpq %r12, %rsi
    jb dec_loop
    jmp seg_fill
dec_run:
    andb $0x7f, %al
    incb %al
    movzbl %al, %ecx               # count = (c&0x7f)+1
    lodsb
    xorb %r11b, %al
    movzbl %al, %eax               # value
    movb %al, %r10b
    movl %ecx, %eax
    movb %r10b, %al                # al = value, rcx = count
    rep stosb
    cmpq %r12, %rsi
    jb dec_loop

seg_fill:
    # zero-fill bss: dst = base+off+filesz, len = memsz-filesz
    movq %r15, %rdi
    addq 0(%r14), %rdi
    addq 8(%r14), %rdi
    movq 16(%r14), %rcx
    subq 8(%r14), %rcx
    xorl %eax, %eax
    rep stosb

    # mprotect(base+off, memsz, prot)
    movq $10, %rax
    movq %r15, %rdi
    addq 0(%r14), %rdi
    movq 16(%r14), %rsi
    movq 24(%r14), %rdx
    syscall

    addq $56, %r14                 # 7 qwords per segmen
    decq %r13
    jnz seg_loop

    # jmp entry (stack tetap utuh dari kernel: argc/argv/envp)
    movq %r15, %rax
    addq @@ENTRY_OFF@@(%rip), %rax
    jmp *%rax

.section .data
min_v:      .quad @@MIN_V@@
range:      .quad @@RANGE@@
mmap_flags: .quad @@FLAGS@@
nsegs:      .quad @@NSEGS@@
entry_off:  .quad @@ENTRY_OFF@@
key:        .byte @@KEY@@
segs:
@@SEGS@@
blob:
@@BLOB@@
"""

# ============================================================
# Stub dynamic (C, -static -nostdlib) — temp file + execve
# ============================================================
STUB_DYN = """/* generated by elfpack.py — dynamic loader (temp file + execve) */
typedef unsigned long ul;
typedef long ll;
typedef unsigned char uc;

static inline ll sc0(ll n) {
    ll r;
    __asm__ volatile("syscall" : "=a"(r) : "a"(n) : "rcx", "r11", "memory");
    return r;
}
static inline ll sc3(ll n, ll a, ll b, ll c) {
    ll r;
    __asm__ volatile("syscall" : "=a"(r) : "a"(n), "D"(a), "S"(b), "d"(c)
                     : "rcx", "r11", "memory");
    return r;
}
static inline ll sc6(ll n, ll a, ll b, ll c, ll d, ll e, ll f) {
    register ll r10 __asm__("r10") = d;
    register ll r8  __asm__("r8")  = e;
    register ll r9  __asm__("r9")  = f;
    ll r;
    __asm__ volatile("syscall" : "=a"(r)
                     : "a"(n), "D"(a), "S"(b), "d"(c), "r"(r10), "r"(r8), "r"(r9)
                     : "rcx", "r11", "memory");
    return r;
}

static void build_path(char *p, ll pid) {
    const char hexd[] = "0123456789abcdef";
    char tmp[20];
    int i = 0;
    do { tmp[i++] = hexd[pid & 0xf]; pid >>= 4; } while (pid && i < 20);
    *p++ = '/'; *p++ = 't'; *p++ = 'm'; *p++ = 'p'; *p++ = '/';
    *p++ = '.'; *p++ = 'e'; *p++ = 'l'; *p++ = 'x'; *p++ = '_';
    while (i) *p++ = tmp[--i];
    *p = 0;
}

static long main_c(long argc, char **argv, char **envp) {
    /* decode seluruh file ELF ke buffer anon */
    ul buf = (ul)sc6(9, 0, @@OUT_LEN@@, 3, 0x22, -1, 0);
    if ((ll)buf < 0) return 1;
    uc *dst = (uc *)buf;
    const uc *src = blob;
    ul left = @@BLOB_LEN@@;
    while (left--) {
        uc c = *src++ ^ @@KEY@@;
        if (c & 0x80) {
            ul n = (c & 0x7f) + 1;
            uc v = *src++ ^ @@KEY@@;
            while (n--) *dst++ = v;
        } else {
            *dst++ = c;
        }
    }

    /* tulis ke file temp unik, lalu execve */
    char path[64];
    build_path(path, sc0(39));                 /* getpid */
    ll fd = sc3(2, (ll)path, 0xC1, 0700);      /* O_WRONLY|O_CREAT|O_EXCL */
    if (fd < 0) return 2;
    uc *p = (uc *)buf;
    ul rem = @@OUT_LEN@@;
    while (rem > 0) {
        ll w = sc3(1, fd, (ll)p, rem);
        if (w <= 0) break;
        p += w;
        rem -= (ul)w;
    }
    sc3(3, fd, 0, 0);

    ll pid = sc0(57);                          /* fork */
    if (pid == 0) {
        sc6(59, (ll)path, (ll)argv, (ll)envp, 0, 0, 0);  /* execve */
        sc3(60, 127, 0, 0);                    /* exec gagal */
    }
    ll st = 0;
    sc6(61, pid, (ll)&st, 0, 0, 0, 0);         /* wait4 */
    sc3(87, (ll)path, 0, 0);                   /* unlink temp */
    return (st >> 8) & 0xff;                   /* status child */
}

__attribute__((naked, noreturn)) void _start(void) {
    __asm__ volatile(
        "movq %rsp, %rbx\\n"
        "movq (%%rbx), %%rdi\\n"          /* argc */
        "leaq 8(%%rbx), %%rsi\\n"         /* argv */
        "leaq 8(%%rbx,%%rdi,8), %%rdx\\n" /* envp = argv + argc + 1 */
        "addq $8, %%rdx\\n"
        "call main_c\\n"
        "movq %%rax, %%rdi\\n"
        "movq $60, %%rax\\n"
        "syscall\\n");
}

static const uc blob[] = {
@@BLOB@@
};
"""


# ============================================================
# ELF parsing
# ============================================================
def parse_elf(path):
    d = open(path, "rb").read()
    if d[:4] != b"\x7fELF":
        sys.exit(f"{path}: bukan ELF")
    if d[4] != 2:
        sys.exit(f"{path}: hanya ELF64")
    if struct.unpack_from("<H", d, 18)[0] != 62:
        sys.exit(f"{path}: hanya x86-64")
    e_type = struct.unpack_from("<H", d, 16)[0]   # 2=ET_EXEC 3=ET_DYN
    e_entry = struct.unpack_from("<Q", d, 24)[0]
    e_phoff = struct.unpack_from("<Q", d, 32)[0]
    e_phentsize = struct.unpack_from("<H", d, 54)[0]
    e_phnum = struct.unpack_from("<H", d, 56)[0]
    segs = []
    for i in range(e_phnum):
        off = e_phoff + i * e_phentsize
        p_type = struct.unpack_from("<I", d, off)[0]
        if p_type != 1:                            # PT_LOAD
            continue
        segs.append((
            struct.unpack_from("<Q", d, off + 8)[0],   # p_offset
            struct.unpack_from("<Q", d, off + 16)[0],  # p_vaddr
            struct.unpack_from("<Q", d, off + 32)[0],  # p_filesz
            struct.unpack_from("<Q", d, off + 40)[0],  # p_memsz
            struct.unpack_from("<I", d, off + 4)[0],   # p_flags
        ))
    if not segs:
        sys.exit(f"{path}: tidak ada PT_LOAD")
    return d, e_type, e_entry, segs


def prot_convert(pf):
    p = 0
    if pf & 4:
        p |= 1   # PF_R -> PROT_READ
    if pf & 2:
        p |= 2   # PF_W -> PROT_WRITE
    if pf & 1:
        p |= 4   # PF_X -> PROT_EXEC
    return p


# ============================================================
# RLE + XOR
# ============================================================
def rle_encode(data):
    """Format: control & 0x80 -> run, count=(c&0x7f)+1 (1..128), value byte.
    control < 0x80 -> literal. Byte >= 0x80 selalu di-encode sebagai run."""
    out = bytearray()
    i, n = 0, len(data)
    while i < n:
        b = data[i]
        j = i + 1
        while j < n and data[j] == b and j - i < 128:
            j += 1
        run = j - i
        if b >= 0x80 or run >= 3:
            out.append(0x80 | (run - 1))
            out.append(b)
            i = j
        else:
            out.append(b)
            i += 1
    return bytes(out)


def xorfy(blob, key):
    return bytes(c ^ key for c in blob)


def blob_lines(b):
    lines = []
    for i in range(0, len(b), 12):
        lines.append("    .byte " + ", ".join("0x%02x" % x for x in b[i:i + 12]))
    return "\n".join(lines)


# ============================================================
# Builders
# ============================================================
def build_static(d, e_type, e_entry, segs, key, out_path):
    min_v = min(s[1] for s in segs)
    max_v = max(s[1] + s[3] for s in segs)
    blob = b""
    seg_lines = []
    for (p_off, p_vaddr, p_filesz, p_memsz, p_flags) in segs:
        data = d[p_off:p_off + p_filesz]
        enc = xorfy(rle_encode(data), key)
        seg_lines.append(f"    .quad {p_vaddr - min_v}      # off")
        seg_lines.append(f"    .quad {p_filesz}      # filesz")
        seg_lines.append(f"    .quad {p_memsz}      # memsz")
        seg_lines.append(f"    .quad {prot_convert(p_flags)}      # prot")
        seg_lines.append(f"    .quad {len(blob)}      # blob_off")
        seg_lines.append(f"    .quad {len(enc)}      # blob_len")
        seg_lines.append("    .quad 0")
        blob += enc
    stub = fill(STUB_STATIC, dict(
        MIN_V=min_v,
        RANGE=max_v - min_v,
        FLAGS=0x22 | (0x10 if e_type == 2 else 0),   # MAP_FIXED utk ET_EXEC
        NSEGS=len(segs),
        ENTRY_OFF=e_entry - min_v,
        KEY=key,
        SEGS="\n".join(seg_lines),
        BLOB=blob_lines(blob),
    ))
    with tempfile.TemporaryDirectory() as td:
        asm = os.path.join(td, "s.s")
        obj = os.path.join(td, "s.o")
        open(asm, "w").write(stub)
        subprocess.run(["as", asm, "-o", obj], check=True)
        try:
            subprocess.run(
                ["ld", "-pie", "--no-dynamic-linker", "-o", out_path, obj],
                check=True,
            )
        except subprocess.CalledProcessError:
            # fallback: biarkan PT_INTERP (ld-linux tetap jalan ke _start)
            subprocess.run(["ld", "-pie", "-e", "_start", "-o", out_path, obj],
                           check=True)
    os.chmod(out_path, 0o755)


def build_dynamic(d, key, out_path):
    enc = xorfy(rle_encode(d), key)
    stub = fill(STUB_DYN, dict(
        BLOB=",\n".join("0x%02x" % x for x in enc),
        BLOB_LEN=len(enc),
        OUT_LEN=len(d),
        KEY=key,
    ))
    with tempfile.TemporaryDirectory() as td:
        src = os.path.join(td, "s.c")
        exe = os.path.join(td, "s")
        open(src, "w").write(stub)
        subprocess.run(
            ["cc", "-static", "-nostdlib", "-fno-stack-protector",
             "-fno-builtin", "-no-pie", "-O2", "-o", exe, src],
            check=True,
        )
        data = open(exe, "rb").read()
    open(out_path, "wb").write(data)
    os.chmod(out_path, 0o755)


def main():
    ap = argparse.ArgumentParser(description="ELF runtime packer (gaya UPX)")
    ap.add_argument("-m", "--mode", choices=["static", "dynamic"], required=True)
    ap.add_argument("-p", "--payload", required=True)
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("-s", "--seed", type=int, default=None)
    args = ap.parse_args()

    d, e_type, e_entry, segs = parse_elf(args.payload)
    key = random.Random(args.seed).randrange(256)

    if args.mode == "static":
        build_static(d, e_type, e_entry, segs, key, args.out)
        kind = "static in-memory loader"
    else:
        build_dynamic(d, key, args.out)
        kind = "dynamic temp+execve loader"

    orig = hashlib.sha256(d).hexdigest()[:16]
    packed = hashlib.sha256(open(args.out, "rb").read()).hexdigest()[:16]
    print(f"packed  : {args.out}  ({kind})")
    print(f"  asli  : {len(d)} bytes  sha256={orig}...")
    print(f"  packed: {os.path.getsize(args.out)} bytes  sha256={packed}...")
    print(f"  ratio : {os.path.getsize(args.out) / len(d):.1%}")


if __name__ == "__main__":
    main()
